### ISSUE TITLE
rtDockerPush: java.lang.ClassNotFoundException: org.apache.commons.lang.BooleanUtils

### ISSUE THREAD

**Issue by tginiotis-at-work** [jfrog/jenkins-artifactory-plugin#625]
**Describe the bug**
When using `rtDockerPush` it gets the following error under plugin version `3.15.2`:

```
INFO: Pushing image: REDACTED
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/BooleanUtils
	at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.build(DefaultDockerClientConfig.java:442)
	at org.jfrog.build.extractor.docker.DockerJavaWrapper.getDockerClient(DockerJavaWrapper.java:76)
	at org.jfrog.build.extractor.docker.DockerJavaWrapper.pushImage(DockerJavaWrapper.java:41)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:84)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:69)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.BooleanUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 6 more
```

but it works fine with version `3.13.2`.

**To Reproduce**
Use `rtDockerPush`.

**Expected behavior**
The built image is pushed to Artifactory

**Versions**
- Jenkins Artifactory plugin version: 3.15.2
- Jenkins operating system: Linux
- Artifactory Version: Enterprise Plus 7.21.23 rev 72123900

**Comment by yahavi** [comment]
@tginiotis-at-work 
Thanks for reporting this issue.

This issue will be fixed soon after the next release of the [docker-java](https://github.com/docker-java/docker-java) library.
As a workaround, you can downgrade to Jenkins Artifactory plugin 3.13.2.

(duplication of https://github.com/jfrog/jenkins-artifactory-plugin/issues/597)

**Comment by yahavi** [comment]
@tginiotis-at-work 
Jenkins Artifactory plugin 3.15.4 is released!
This version includes #629, which should resolve this issue. Feel free to upgrade.
We'd appreciate your feedback on that.

**Comment by tginiotis-at-work** [comment]
@yahavi `rtDockerPush` works now. Thanks
