### ISSUE TITLE
Dependency on commons-lang-2.4.jar needs updating

### ISSUE THREAD

**Issue by nhtones** [jfrog/jenkins-artifactory-plugin#556]
**Describe the bug**
Attempting to run release builds on latest version of jenkins 2.309 receiving errors starting maven release builds.

WARNING: LinkageError while performing UserRequest:hudson.maven.Maven3Builder@165e1e10
java.lang.NoSuchMethodError: org/apache/commons/lang/StringUtils.endsWithAny(Ljava/lang/String;[Ljava/lang/String;)Z (loaded from file:/home/jenkins/cache/artifactory-plugin/3.13.0/commons-lang-2.4.jar by ClassRealm[plexus.core, parent: null]) called from class org.jenkins.ui.icon.Icon (loaded from <Unknown> by hudson.remoting.RemoteClassLoader@91db564f).

Updating to plugin 3.13.1 also received the same error message.

We have manually updated commons-lang to 2.6 and placed it in the /home/jenkins/cache/artifactory-plugin/3.13.1/ directory and the problem has been resolved and builds continue as expected

**To Reproduce**
Attempt any maven build in environment

**Expected behavior**
Release plugin runs and uploads build artifacts to artifactory.

**Screenshots**
N/A

**Versions**
- Jenkins Artifactory plugin version:  3.13.1
- Jenkins operating system: linux 
- Artifactory Version: 7.23.3

**Additional context**
Complete stack trace

ERROR: Failed to parse POMs
java.io.IOException: Remote call on Channel to Maven [/home/jenkins/tools/jdk-11.0.8+10/bin/java, -Xmx512m, -XX:MaxPermSize=1024m, -cp, /home/jenkins/plugins/maven-plugin/WEB-INF/lib/maven35-agent-1.13.jar:/home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/M3/boot/plexus-classworlds-2.5.2.jar:/home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/M3/conf/logging, jenkins.maven3.agent.Maven35Main, /home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/M3, /var/cache/jenkins/war/WEB-INF/lib/remoting-4.10.jar, /home/jenkins/plugins/maven-plugin/WEB-INF/lib/maven35-interceptor-1.13.jar, /home/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.13.jar, 35619] failed
	at hudson.remoting.Channel.call(Channel.java:1005)
	at hudson.maven.ProcessCache$MavenProcess.call(ProcessCache.java:161)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:877)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:516)
	at hudson.model.Run.execute(Run.java:1889)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:100)
	at hudson.model.Executor.run(Executor.java:433)
Caused by: java.lang.NoSuchMethodError: org/apache/commons/lang/StringUtils.endsWithAny(Ljava/lang/String;[Ljava/lang/String;)Z (loaded from file:/home/jenkins/cache/artifactory-plugin/3.13.0/commons-lang-2.4.jar by ClassRealm[plexus.core, parent: null]) called from class org.jenkins.ui.icon.Icon (loaded from <Unknown> by hudson.remoting.RemoteClassLoader@91db564f).
	at org.jenkins.ui.icon.Icon.toNormalizedIconName(Icon.java:221)
	at hudson.model.BallColor.<init>(BallColor.java:82)
	at hudson.model.BallColor.<clinit>(BallColor.java:57)
	at hudson.model.Result.<clinit>(Result.java:58)
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:342)
	at com.sun.proxy.$Proxy5.<clinit>(Unknown Source)
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor49.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.io.ObjectStreamClass.newInstance(ObjectStreamClass.java:1092)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2272)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1790)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2563)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2455)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2288)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1790)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:566)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:476)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2422)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2288)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1790)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2563)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2455)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2288)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1790)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:566)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:476)
	at hudson.remoting.UserRequest.deserialize(UserRequest.java:289)
	at hudson.remoting.UserRequest.perform(UserRequest.java:189)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at hudson.remoting.InterceptingExecutorService$$Lambda$34/0000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to Channel to Maven [/home/jenkins/tools/jdk-11.0.8+10/bin/java, -Xmx512m, -XX:MaxPermSize=1024m, -cp, /home/jenkins/plugins/maven-plugin/WEB-INF/lib/maven35-agent-1.13.jar:/home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/M3/boot/plexus-classworlds-2.5.2.jar:/home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/M3/conf/logging, jenkins.maven3.agent.Maven35Main, /home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/M3, /var/cache/jenkins/war/WEB-INF/lib/remoting-4.10.jar, /home/jenkins/plugins/maven-plugin/WEB-INF/lib/maven35-interceptor-1.13.jar, /home/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.13.jar, 35619]
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1795)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.maven.ProcessCache$MavenProcess.call(ProcessCache.java:161)
		at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:877)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:516)
		at hudson.model.Run.execute(Run.java:1889)
		at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
		at hudson.model.ResourceController.execute(ResourceController.java:100)
		at hudson.model.Executor.run(Executor.java:433)

**Comment by nhtones** [comment]
This is continuing in plugin version 3.13.2

**Comment by santhoshjfrog** [comment]
I'm seeing the behavior with the below combination:
Jenkins version - 2.319.1
Artifactory plugin version - 3.13.2
Maven Integration plugin version - 3.10

**Comment by pratap8482** [comment]
> I'm seeing the behavior with the below combination: Jenkins version - 2.319.1 Artifactory plugin version - 3.13.2 Maven Integration plugin version - 3.10 <img alt="Screen Shot 2021-12-02 at 2 49 05 PM" width="1676" src="https://user-images.githubusercontent.com/72781174/144515950-018a2374-b37b-4806-9ab7-67f587c4bf70.png"> <img alt="Screen Shot 2021-12-02 at 2 48 59 PM" width="1674" src="https://user-images.githubusercontent.com/72781174/144515952-7a482a7b-6bab-4e20-88b4-166f17d3d85f.png">

i am getting same issue

**Comment by yahavi** [comment]
@nhtones @santhoshjfrog 
The dependency update is included in the latest release of the Jenkins Artifactory plugin - 3.14.2.
We'd appreciate your feedback on that.
