### ISSUE TITLE
NoSuchMethodError in version 3.16.1

### ISSUE THREAD

**Issue by tolearyatwth** [jfrog/jenkins-artifactory-plugin#655]
**Describe the bug**
Similar to bug #556 after upgrading from 3.13.2 to 3.16.1 I am getting the following error message when running maven builds:

16:55:16 [ERROR] org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionStarted() listener has failed: 
16:55:16 java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.firstNonBlank([Ljava/lang/CharSequence;)Ljava/lang/CharSequence;

I downgraded back to 3.13.2 and the builds ran fine. Also based on the bug #556  I did replace the commons-lang with 2.6 version. 

**Common-lang jars in 3.16.1:**
commons-lang3-3.8.1.jar

**Common-lang jars in 3.13.2:**
commons-lang3-3.8.1.jar
commons-lang-2.6.jar
Deleted - commons-lang-2.4.jar

I attempted to put the commons-lang-2.6.jar in the 3.16.1 to see if that would fix the issue but I got the same error as above. 

**To Reproduce**
Attempt any maven build in environment.

**Expected behavior**
Release plugin runs and uploads build artifacts to artifactory.

**Screenshots**
None.

**Versions**
- Jenkins Core version: 2.337
- Jenkins Artifactory plugin version: 3.16.1
- Jenkins operating system: windows server 2012
- Artifactory Version: 7.33.9

**Additional context**
Full stack trace:

16:55:16 [INFO] Initializing Artifactory Build-Info Recording
16:55:16 [ERROR] org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionStarted() listener has failed: 
16:55:16 java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.firstNonBlank([Ljava/lang/CharSequence;)Ljava/lang/CharSequence;
16:55:16 	at org.jfrog.build.extractor.maven.BuildInfoModelPropertyResolver.resolveCoreProperties(BuildInfoModelPropertyResolver.java:123)
16:55:16 	at org.jfrog.build.extractor.maven.BuildInfoModelPropertyResolver.resolveProperties(BuildInfoModelPropertyResolver.java:36)
16:55:16 	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionStarted(BuildInfoRecorder.java:144)
16:55:16 	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:61)
16:55:16 	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
16:55:16 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:74)
16:55:16 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
16:55:16 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
16:55:16 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
16:55:16 	at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main(Maven35Launcher.java:130)
16:55:16 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:55:16 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:55:16 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:55:16 	at java.lang.reflect.Method.invoke(Method.java:497)
16:55:16 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
16:55:16 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
16:55:16 	at jenkins.maven3.agent.Maven35Main.launch(Maven35Main.java:178)
16:55:16 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:55:16 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:55:16 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:55:16 	at java.lang.reflect.Method.invoke(Method.java:497)
16:55:16 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
16:55:16 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
16:55:16 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
16:55:16 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
16:55:16 	at hudson.remoting.Request$2.run(Request.java:375)
16:55:16 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
16:55:16 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:55:16 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
16:55:16 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
16:55:16 	at java.lang.Thread.run(Thread.java:745)
16:55:16 [ERROR] Internal error: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionStarted() listener has failed: org.apache.commons.lang3.StringUtils.firstNonBlank([Ljava/lang/CharSequence;)Ljava/lang/CharSequence; -> [Help 1]
16:55:16 org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionStarted() listener has failed: 
16:55:16 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:122)
16:55:16 	at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main(Maven35Launcher.java:130)
16:55:16 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:55:16 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:55:16 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:55:16 	at java.lang.reflect.Method.invoke(Method.java:497)
16:55:16 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
16:55:16 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
16:55:16 	at jenkins.maven3.agent.Maven35Main.launch(Maven35Main.java:178)
16:55:16 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:55:16 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:55:16 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:55:16 	at java.lang.reflect.Method.invoke(Method.java:497)
16:55:16 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
16:55:16 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
16:55:16 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
16:55:16 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
16:55:16 	at hudson.remoting.Request$2.run(Request.java:375)
16:55:16 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
16:55:16 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:55:16 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
16:55:16 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
16:55:16 	at java.lang.Thread.run(Thread.java:745)
16:55:16 Caused by: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionStarted() listener has failed: 
16:55:16 	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionStarted(BuildInfoRecorder.java:154)
16:55:16 	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:61)
16:55:16 	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
16:55:16 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:74)
16:55:16 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
16:55:16 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
16:55:16 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
16:55:16 	... 22 more
16:55:16 Caused by: java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.firstNonBlank([Ljava/lang/CharSequence;)Ljava/lang/CharSequence;
16:55:16 	at org.jfrog.build.extractor.maven.BuildInfoModelPropertyResolver.resolveCoreProperties(BuildInfoModelPropertyResolver.java:123)
16:55:16 	at org.jfrog.build.extractor.maven.BuildInfoModelPropertyResolver.resolveProperties(BuildInfoModelPropertyResolver.java:36)
16:55:16 	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionStarted(BuildInfoRecorder.java:144)
16:55:16 	... 28 more
16:55:16 [ERROR] 
16:55:16 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
16:55:16 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
16:55:16 [ERROR] 
16:55:16 [ERROR] For more information about the errors and possible solutions, please read the following articles:
16:55:16 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by yahavi** [comment]
Thanks for reporting this issue, @tolearyatwth!
We created https://github.com/jfrog/build-info/pull/633 to handle it. The fix is expected to be included in the next Jenkins Artifactory plugin release.
We'll keep you updated.

**Comment by fraz3alpha** [comment]
@yahavi  - it has been nearly a month since you created a fix in an upstream library, but there has been no new artifactory plugin release to incorporate it, so this still remains an issue. Please can you release a new plugin version with this fix in so that this issue can really be closed.

**Comment by eyalbe4** [comment]
@fraz3alpha,
A new release of the plugin which includes this fix is planned to become available during next week.

**Comment by yahavi** [comment]
@fraz3alpha @tolearyatwth,
Jenkins Artifactory plugin 3.16.2 is released. This version includes a fix for this issue.
Feel free to upgrade - we'd appreciate your feedback on that.
